### ISSUE TITLE
Experience Cloud Login Page is not detected in Interaction Studio site map 

### ISSUE THREAD

**Issue by naveenvm93** [salesforce-experiencecloud/interaction-studio-content-personalization#1]
With the current site map code, Experience cloud login page is not detected.

Request to change the code from 

`                isMatch: () => window.location.pathname.includes("/s/login/")
`

To 

`                isMatch: () => /\/login/.test(window.location.href)
`

Then the login page will get detected in the sitemap.

**Comment by sagadzhanovSF** [comment]
Hi @naveenvm93 
Sitemap in this repository is provided as an example and will always require modifications based on the real implementation on the Experience Cloud side.
Therefore I am closing this issue
